
import React, { useState, useMemo } from 'react';
import { useData } from '../../context/DataContext';
import { Client, ProductType, UserRole } from '../../types';
import { Search, Filter, Download, Edit2, X, Mail, Phone, Shield, FileDigit } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export const Clients: React.FC = () => {
  const { clients, updateClient, user } = useData();
  const [searchTerm, setSearchTerm] = useState('');
  const [productFilter, setProductFilter] = useState<string>('All');
  
  // Edit State
  const [editingClient, setEditingClient] = useState<Client | null>(null);
  const [editForm, setEditForm] = useState<Partial<Client>>({});

  const filteredClients = useMemo(() => {
    let result = clients;
    
    // Role based filtering
    if (user?.role === UserRole.ADVISOR && user.productsSold) {
        result = result.filter(c => user.productsSold!.includes(c.product));
    }

    if (productFilter !== 'All') {
        result = result.filter(c => c.product === productFilter);
    }

    if (searchTerm) {
        const lower = searchTerm.toLowerCase();
        result = result.filter(c => 
            c.name.toLowerCase().includes(lower) || 
            c.policyNumber.toLowerCase().includes(lower) ||
            c.email?.toLowerCase().includes(lower)
        );
    }
    
    return result;
  }, [clients, user, productFilter, searchTerm]);

  const handleEdit = (client: Client) => {
      setEditingClient(client);
      setEditForm({...client});
  };

  const handleSave = (e: React.FormEvent) => {
      e.preventDefault();
      if (editingClient && editForm) {
          updateClient(editingClient.id, editForm);
          setEditingClient(null);
      }
  };

  const getStatusText = (renewalDate: string) => {
      const today = new Date();
      const renewal = new Date(renewalDate);
      const diffTime = renewal.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays < 0) return 'Expired';
      if (diffDays < 30) return 'Renewing Soon';
      return 'Active';
  };

  const generatePDF = () => {
    const doc = new jsPDF({ orientation: 'landscape' });
    
    doc.setFontSize(22);
    doc.setTextColor(11, 34, 64); // NHFG Dark Blue
    doc.text("Advisor Client Portfolio", 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text(`Generated by: ${user?.name || 'NHFG Advisor'}`, 14, 30);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 35);
    doc.text(`Total Clients: ${filteredClients.length}`, 14, 40);

    const tableColumn = ["Client Name", "Email", "Phone", "Product Category", "Policy #", "Carrier", "Annual Premium", "Status", "Renewal"];
    const tableRows: any[] = [];

    filteredClients.forEach(client => {
      const clientData = [
        client.name,
        client.email || 'N/A',
        client.phone || 'N/A',
        client.product,
        client.policyNumber,
        client.carrier || 'N/A',
        `$${client.premium.toLocaleString()}`,
        getStatusText(client.renewalDate),
        new Date(client.renewalDate).toLocaleDateString(),
      ];
      tableRows.push(clientData);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 48,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [11, 34, 64], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    doc.save(`NHFG_Portfolio_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const getStatusColor = (renewalDate: string) => {
      const today = new Date();
      const renewal = new Date(renewalDate);
      const diffTime = renewal.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays < 0) return 'bg-white text-red-700 border-red-300 shadow-sm'; // Expired
      if (diffDays < 30) return 'bg-white text-orange-700 border-orange-300 shadow-sm'; // Renewing Soon
      return 'bg-white text-green-700 border-green-300 shadow-sm'; // Active
  };

  return (
    <div className="space-y-8 pb-10">
        <div className="flex flex-col md:flex-row justify-between items-end gap-4">
            <div>
                <h1 className="text-4xl font-black text-[#0B2240] tracking-tight">Client Management</h1>
                <p className="text-slate-500 font-bold">Monitor policies and renewal cycles.</p>
            </div>
            <button 
                onClick={generatePDF}
                className="bg-white border-2 border-slate-100 text-slate-700 px-8 py-4 rounded-full font-black text-sm hover:bg-slate-50 shadow-xl transition-all flex items-center gap-2 transform active:scale-95"
            >
                <Download className="h-5 w-5" /> Export Portfolio
            </button>
        </div>

        <div className="bg-white rounded-[3.5rem] shadow-2xl border border-slate-100 overflow-hidden">
            {/* Search Filters */}
            <div className="p-8 border-b border-slate-100 flex flex-col md:flex-row gap-6 bg-slate-50/50">
                <div className="relative flex-1">
                    <Search className="absolute left-5 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400" />
                    <input 
                        type="text" 
                        placeholder="Search by name, policy or email..." 
                        value={searchTerm}
                        onChange={e => setSearchTerm(e.target.value)}
                        className="w-full pl-14 pr-8 py-5 bg-white border-2 border-slate-100 rounded-[2rem] text-sm font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-500 outline-none text-slate-900 shadow-sm transition-all"
                    />
                </div>
                <div className="relative">
                    <select 
                        className="bg-white text-slate-700 border-2 border-slate-100 rounded-[2rem] px-10 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 focus:border-blue-500 appearance-none pr-14 cursor-pointer shadow-sm transition-all"
                        value={productFilter}
                        onChange={e => setProductFilter(e.target.value)}
                    >
                        <option value="All">All Categories</option>
                        {Object.values(ProductType).map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                    <Filter className="absolute right-6 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 pointer-events-none" />
                </div>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead className="text-[11px] uppercase font-black tracking-[0.15em]">
                        <tr>
                            <th className="px-10 py-6 bg-slate-100 text-slate-600 border-r-4 border-white">Client Name</th>
                            <th className="px-10 py-6 bg-blue-100 text-blue-800 border-r-4 border-white">Policy Info</th>
                            <th className="px-10 py-6 bg-indigo-100 text-indigo-800 border-r-4 border-white">Premium</th>
                            <th className="px-10 py-6 bg-amber-100 text-amber-800 border-r-4 border-white">Status</th>
                            <th className="px-10 py-6 bg-emerald-100 text-emerald-800 border-r-4 border-white">Contact</th>
                            <th className="px-10 py-6 bg-purple-100 text-purple-800 border-r-4 border-white">Carrier</th>
                            <th className="px-10 py-6 bg-slate-100 text-slate-600">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y-8 divide-white">
                        {filteredClients.map(client => (
                            <tr key={client.id} className="group hover:scale-[1.005] transition-transform duration-200">
                                <td className="px-10 py-8 bg-slate-50 border-r-4 border-white first:rounded-l-[2rem]">
                                    <div className="font-black text-[#0B2240] text-lg">{client.name}</div>
                                    <div className="text-xs text-slate-400 font-bold mt-1 uppercase tracking-wide">{client.city}, {client.state}</div>
                                </td>
                                <td className="px-10 py-8 bg-blue-50 border-r-4 border-white">
                                    <div className="font-black text-blue-900 text-sm">{client.product}</div>
                                    <div className="text-xs text-blue-600 font-black font-mono mt-2 bg-white/60 px-2 py-1 rounded inline-block shadow-sm">{client.policyNumber}</div>
                                </td>
                                <td className="px-10 py-8 bg-indigo-50 border-r-4 border-white font-mono font-black text-indigo-700 text-xl">
                                    ${client.premium.toLocaleString()}
                                </td>
                                <td className="px-10 py-8 bg-amber-50 border-r-4 border-white">
                                    <span className={`px-4 py-2 rounded-2xl text-[10px] font-black uppercase border-2 shadow-sm inline-block ${getStatusColor(client.renewalDate)}`}>
                                        {getStatusText(client.renewalDate)}
                                    </span>
                                    <div className="text-[10px] text-amber-800/60 font-black mt-3 uppercase tracking-widest">EXP: {new Date(client.renewalDate).toLocaleDateString()}</div>
                                </td>
                                <td className="px-10 py-8 bg-emerald-50 border-r-4 border-white">
                                    <div className="flex gap-3">
                                        {client.email && (
                                            <a href={`mailto:${client.email}`} className="p-3 bg-white text-emerald-700 rounded-2xl shadow-sm hover:bg-emerald-600 hover:text-white transition-all border-2 border-emerald-100" title={client.email}>
                                                <Mail className="h-5 w-5" />
                                            </a>
                                        )}
                                        {client.phone && (
                                            <a href={`tel:${client.phone}`} className="p-3 bg-white text-emerald-700 rounded-2xl shadow-sm hover:bg-emerald-600 hover:text-white transition-all border-2 border-emerald-100" title={client.phone}>
                                                <Phone className="h-5 w-5" />
                                            </a>
                                        )}
                                    </div>
                                </td>
                                <td className="px-10 py-8 bg-purple-50 border-r-4 border-white text-sm font-black text-purple-800 uppercase tracking-widest">
                                    {client.carrier || 'N/A'}
                                </td>
                                <td className="px-10 py-8 bg-slate-50 last:rounded-r-[2rem] text-right">
                                    <button 
                                        onClick={() => handleEdit(client)}
                                        className="p-4 bg-white hover:bg-blue-600 hover:text-white rounded-[1.25rem] text-slate-400 shadow-lg border-2 border-slate-100 transition-all active:scale-90 transform group-hover:scale-110"
                                    >
                                        <Edit2 className="h-6 w-6" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                        {filteredClients.length === 0 && (
                            <tr>
                                <td colSpan={7} className="px-10 py-32 text-center text-slate-300 font-black text-2xl uppercase tracking-[0.2em] bg-slate-50 rounded-[2rem]">
                                    <Shield className="h-24 w-24 mx-auto mb-6 opacity-10" />
                                    Database Empty
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>

        {/* Edit Modal - Vivid Style */}
        {editingClient && (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0B2240]/70 backdrop-blur-xl p-6 animate-fade-in">
                <div className="bg-white rounded-[3.5rem] shadow-[0_0_100px_rgba(0,0,0,0.3)] w-full max-w-2xl p-12 relative max-h-[90vh] overflow-y-auto border border-white/20">
                    <div className="flex justify-between items-center mb-10">
                        <div className="flex items-center gap-5">
                            <div className="p-5 bg-blue-600 text-white rounded-[1.5rem] shadow-xl shadow-blue-600/20">
                                <Edit2 className="h-8 w-8" />
                            </div>
                            <div>
                                <h2 className="text-3xl font-black text-[#0B2240] tracking-tight">Edit Client Account</h2>
                                <p className="text-slate-400 font-bold uppercase text-[10px] tracking-widest mt-1">Advisor Administrative Console</p>
                            </div>
                        </div>
                        <button onClick={() => setEditingClient(null)} className="p-4 hover:bg-slate-100 rounded-full transition-colors"><X className="h-8 w-8 text-slate-300" /></button>
                    </div>
                    
                    <form onSubmit={handleSave} className="space-y-8">
                        {/* Identitiy Block */}
                        <div className="bg-slate-50 p-10 rounded-[2.5rem] border-2 border-slate-100 space-y-8">
                            <h3 className="text-[11px] font-black text-slate-400 uppercase tracking-[0.3em] flex items-center gap-3">
                                <span className="h-1.5 w-1.5 bg-blue-600 rounded-full"></span> 
                                Account Identity
                            </h3>
                            <div>
                                <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Legal Full Name</label>
                                <input 
                                    className="w-full bg-white text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-base font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-600 outline-none shadow-sm transition-all"
                                    value={editForm.name || ''}
                                    onChange={e => setEditForm({...editForm, name: e.target.value})}
                                />
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Email Address</label>
                                    <input 
                                        type="email"
                                        className="w-full bg-white text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-base font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-600 outline-none shadow-sm transition-all"
                                        value={editForm.email || ''}
                                        onChange={e => setEditForm({...editForm, email: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Primary Phone</label>
                                    <input 
                                        type="tel"
                                        className="w-full bg-white text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-base font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-600 outline-none shadow-sm transition-all"
                                        value={editForm.phone || ''}
                                        onChange={e => setEditForm({...editForm, phone: e.target.value})}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Policy Block */}
                        <div className="bg-white p-10 rounded-[2.5rem] border-4 border-blue-50 space-y-8 shadow-sm">
                            <h3 className="text-[11px] font-black text-blue-400 uppercase tracking-[0.3em] flex items-center gap-3">
                                <span className="h-1.5 w-1.5 bg-blue-600 rounded-full"></span> 
                                Policy Administration
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div className="md:col-span-2">
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Master Policy Number</label>
                                    <input 
                                        className="w-full bg-blue-50/30 text-[#0B2240] border-2 border-blue-100 rounded-2xl px-6 py-6 text-2xl font-black font-mono focus:ring-4 focus:ring-blue-200 outline-none transition-all"
                                        value={editForm.policyNumber || ''}
                                        onChange={e => setEditForm({...editForm, policyNumber: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Coverage Product</label>
                                    <select 
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none appearance-none cursor-pointer"
                                        value={editForm.product}
                                        onChange={e => setEditForm({...editForm, product: e.target.value as ProductType})}
                                    >
                                        {Object.values(ProductType).map(p => <option key={p} value={p}>{p}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Issuing Carrier</label>
                                    <input 
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none"
                                        value={editForm.carrier || ''}
                                        onChange={e => setEditForm({...editForm, carrier: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Annual Premium ($)</label>
                                    <input 
                                        type="number"
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none"
                                        value={editForm.premium || ''}
                                        onChange={e => setEditForm({...editForm, premium: Number(e.target.value)})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Renewal Date</label>
                                    <input 
                                        type="date"
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none"
                                        value={editForm.renewalDate || ''}
                                        onChange={e => setEditForm({...editForm, renewalDate: e.target.value})}
                                    />
                                </div>
                            </div>
                        </div>

                        <div className="pt-10 flex gap-6">
                            <button type="button" onClick={() => setEditingClient(null)} className="flex-1 py-6 rounded-full font-black text-slate-400 bg-slate-100 hover:bg-slate-200 transition-all uppercase tracking-widest text-xs">Discard</button>
                            <button type="submit" className="flex-1 py-6 rounded-full font-black bg-[#0B2240] text-white hover:bg-blue-800 transition-all shadow-2xl shadow-blue-900/30 transform active:scale-95 uppercase tracking-widest text-xs">Commit Updates</button>
                        </div>
                    </form>
                </div>
            </div>
        )}
    </div>
  );
};
